server:
  port: 8085

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: gateway,metrics

spring:
  cloud:
    gateway:
      routes:
        - id: web-service
          uri: lb://web-service
          predicates:
            - Path=/api/web/**
        - id: hotel-service
          uri: lb://hotel-service
          predicates:
            - Path=/api/hotels/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**

eureka:
  instance:
    hostname: ${HOST_NAME:localhost}
  client:
    serviceUrl:
      defaultZone: http://localhost:8889/eureka