server:
 port: 8085

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: gateway,metrics

spring:
  cloud:
    gateway:
      defaultFilters: TokenRelay

      routes:
        - id: web-service
        uri: lb://web-service

        - id: hotel-service
        uri: lb://hotel-service

        -id: user-service
        uri: lb://user-service

eureka:
  instance:
    hostname: ${HOST_NAME:localhost}
  client:
    serviceUrl:
      defaultZone: http://localhost:8889/eureka